wget -O gunicorn.service -q --show-progress https://raw.github.com/kevintee23/smartdb/master/gunicorn.service
wget -O hook.py -q --show-progress https://raw.github.com/kevintee23/smartdb/master/hook.py
wget -O takepicture.py -q --show-progress https://raw.github.com/kevintee23/smartdb/master/takepicture.py
wget -O templates/gallery.html -q --show-progress https://raw.github.com/kevintee23/smartdb/master/templates/gallery.html
wget -O templates/picture.html -q --show-progress https://raw.github.com/kevintee23/smartdb/master/templates/picture.html
wget -O scripts/add_collection.py -q --show-progress https://raw.github.com/kevintee23/smartdb/master/scripts/add_collection.py
wget -O scripts/add_image.py -q --show-progress https://raw.github.com/kevintee23/smartdb/master/scripts/add_image.py
wget -O scripts/del_collections.py -q --show-progress https://raw.github.com/kevintee23/smartdb/master/scripts/del_collections.py
wget -O scripts/del_faces.py -q --show-progress https://raw.github.com/kevintee23/smartdb/master/scripts/del_faces.py
wget -O README.md -q --show-progress https://raw.github.com/kevintee23/smartdb/master/README.md
